# Generated by Django 3.2.8 on 2021-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealID', models.TextField()),
                ('dealTitle', models.TextField()),
                ('dealInfo', models.TextField()),
                ('price', models.TextField()),
                ('store', models.TextField()),
                ('ratingNum', models.TextField()),
                ('activityCol', models.TextField()),
                ('lastPostCol', models.TextField()),
                ('dealImg', models.TextField()),
                ('dealLink', models.TextField()),
                ('dealPostLink', models.TextField()),
            ],
        ),
    ]
