# Generated by Django 3.2.8 on 2021-10-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='dealID',
        ),
    ]
