# Generated by Django 3.2.8 on 2021-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_chek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chek',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
