# Generated by Django 3.2.8 on 2021-10-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_alter_chek_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chek',
        ),
    ]
